import { Feed } from "@/components/Feed";
import { Prompt } from "@/components/Prompt";
import Head from "next/head";
import Link from "next/link";
import styled from "styled-components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Prompt />
      <CreateContainer>
        <Link href="/canvas" style={{ textDecoration: "none" }}>
          <Create>Create a post of your own here!</Create>
        </Link>
      </CreateContainer>

      <Feed />
    </>
  );
}

const CreateContainer = styled.div`
  display: flex;
  justify-content: center;
  margin: 20px auto;
`;

const Create = styled.button`
  display: flex;
  justify-content: center;
  align-items: center;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  font-size: 18px;
  font-weight: 600;
  border: none;
  padding: 16px 32px;
  color: white;
  border-radius: 12px;
  transition: all 0.3s ease;
  box-shadow: 0 4px 12px rgba(102, 126, 234, 0.3);
  min-width: 280px;

  &:hover {
    cursor: pointer;
    transform: translateY(-2px);
    box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);
  }

  &:active {
    transform: translateY(0);
  }

  @media (max-width: 480px) {
    font-size: 16px;
    padding: 14px 28px;
    min-width: 240px;
  }
`;
