import { Feed } from "@/components/Feed";
import { Navbar } from "@/components/NavbarNew";
import { Prompt } from "@/components/Prompt";
import Head from "next/head";
import Link from "next/link";
import styled from "styled-components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Prompt />
      <div
        style={{ display: "flex", justifyContent: "center", margin: "20px 0" }}
      >
        <Link href="/canvas" style={{ textDecoration: "none" }}>
          <Create>Create a post of your own here!</Create>
        </Link>
      </div>

      <Feed />
    </>
  );
}

const Create = styled.button`
  display: flex;
  justify-content: center;
  background-color: black;
  font-family: "Tiny5";
  font-size: 20px;
  border: none;
  padding: 5px 10px;
  color: white;

  &:hover {
    background-color: white;
    color: black;
  }
`;
